### ISSUE TITLE
Question: what to do for other start-points of the app? And customized themes?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [DreaminginCodeZH/MaterialColdStart#1]
I have an app that shows an app-widget settings screen when creating an app-widget, and not just the normal launching of the app.
Not only that, but the user can choose which theme to use on the entire app.

How would you deal with that?

**Comment by zhanghai** [comment]
You can specify different themes for different activities, so launching from AppWidget or Launcher should not be a problem since each activity can normally have a stable preview.

As for dynamic theming, it will not be easy because the manifest in Android is static. You can checkout [the <activity-alias> tag](http://developer.android.com/guide/topics/manifest/activity-alias-element.html).

This is the way apps like SuperSU implement customizable launcher icons, by dynamically enabling/disabling among a set of activities. The possible tradeoff is losing the shortcuts user created on home screen - This is only my suspect, because I've never tried it out personally.

**Comment by AndroidDeveloperLB** [comment]
That's too bad. Thanks anyway.
